### ISSUE TITLE
Отсутствует гиперссылка

### ISSUE THREAD

**Issue by mirrinda** [savushkin-r-d/T1-PLCnext-Demo#35]
нет гиперссылки на WinSCP
Откройте командную оболочку с помощью инструмента командной строки (например, [PuTTY](https://www.putty.org/), в WinSCP сочетание клавиш Ctrl+P)

**Comment by idzm** [comment]
Ссылка на программу присутствует в документе ранее - https://github.com/savushkin-r-d/T1-PLCnext-Demo/blob/e7abef87442fd538103c51e1a0697fd1f10891da/docs/README.MD#обновление-прошивки-контроллера-через-командную-оболочку.
